dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "951c4df14ece342411f8a8b87e977a3f259acbb7"
    token:
      secure: "951c4df14ece342411f8a8b87e977a3f259acbb7"
jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
